name: Java CI - Specific Test

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: Run Specific Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        test-file: 
          - org.telegram.telegrambots.meta.api.methods.send.TestSendMessage
          - org.telegram.telegrambots.meta.api.methods.send.TestSendMediaGroup
          - org.telegram.telegrambots.meta.api.methods.TestGetUpdates
          - org.telegram.telegrambots.meta.api.methods.TestSetGameScore

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' 
          java-version: '17'
          cache: maven  
          
      - name: Run Specific Test
        run: |
          cd telegrambots-meta
          mvn test -Dtest=${{ matrix.test-file }}
